  
steps:
- name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
  args: ['gcloud', 'builds', 'submit', '--tag','${_IMAGE_NAME}', '.']
- name: 'gcr.io/cloud-builders/kubectl'
  args: ['set', 'image','deployment/${_K8SDEPLOYMENT}','${_K8SDEPLOYMENT}=${_IMAGE_NAME}']
  env:
  - 'CLOUDSDK_COMPUTE_ZONE=${_ZONE}'
  - 'CLOUDSDK_CONTAINER_CLUSTER=${_CLUSTER}'
substitutions:
  _CLUSTER: 'cluster-2'
  _ZONE: 'us-central1-c'
  _K8SDEPLOYMENT: 'demo-ui'
  _TAG_NAME: $SHORT_SHA
  _IMAGE_NAME: 'gcr.io/dtc092021-300-instructor/external:${_TAG_NAME}'